"""Utworzenie tabel

Revision ID: 6f0e131f0f6a
Revises: 
Create Date: 2026-01-03 14:50:14.721360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0e131f0f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wpis', sa.String(length=500), nullable=False),
    sa.Column('kwota_zmiany', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magazyn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wartosc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo')
    op.drop_table('magazyn')
    op.drop_table('historia')
    # ### end Alembic commands ###
